pub mod queries;
pub mod sql_helpers;
pub mod extensions;
mod conn;

use std::borrow::Cow;
pub use auto_table_derive::AutoTable;

use crate::sql_helpers::{generate_create_table, get_columns, no_params};
use std::collections::HashSet;
use log::debug;
use serde::Serialize;
use async_trait::async_trait;

pub type BoxError = Box<dyn std::error::Error + Send + Sync>;

#[repr(u8)]
#[derive(Debug)]
pub enum SqlError {
    ColumnCountMismatch,
    InvalidData(String),
    SerializationIssue(String),
}

// Mark: Column Definition

#[derive(Debug, Clone)]
pub struct ColumnDefinition {
    pub name: &'static str,
    pub sql_type: String,
    pub nullable: bool,
    pub primary_key: bool,
    pub sort_by: Option<String>,
    pub default: Option<String>,
}

impl ColumnDefinition {
    /// Renders this column as a SQL column definition fragment.
    /// e.g. `"id INTEGER PRIMARY KEY"` or `"nonce_id INTEGER DEFAULT 0"`
    pub fn to_sql(&self) -> String {
        let mut parts = vec![format!("{} {}", self.name, self.sql_type)];
        if self.primary_key {
            parts.push("PRIMARY KEY".to_string());
        } else if !self.nullable {
            parts.push("NOT NULL".to_string());
        }
        if let Some(d) = &self.default {
            parts.push(format!("DEFAULT {}", d));
        }
        parts.join(" ")
    }
}

// Mark: AutoTable trait

/// Generated by `#[derive(AutoTable)]`.
pub trait AutoTable {
    fn table_name() -> &'static str;
    fn indexes() -> Option<String>;
    fn column_definitions() -> Vec<ColumnDefinition>;
    fn to_sql_values(&self) -> Result<Vec<AtValue>, SqlError>;
    fn from_sql_values(values: &[AtValue]) -> Result<Self, SqlError> where Self: Sized;

    fn get_id_column() -> Option<ColumnDefinition> {
        Self::column_definitions().iter().find(|d| d.primary_key).map(|d| d.clone())
    }
    fn get_sort_columns() -> Vec<ColumnDefinition> {
        Self::column_definitions().iter().filter(|d| d.sort_by.is_some()).map(|d| d.clone()).collect()
    }
}

/// Codec for custom sql value serialization
pub trait AtSqlCodec {
    fn to_sql(&self) -> impl AtIntoValue;
    fn from_sql(value: &AtValue) -> Result<Self, SqlError> where Self: Sized;
}

/// Abstraction layer for connection
#[async_trait]
pub trait AtConnection: Sized + Send + Sync {
    type Rows: AtRows;
    type Statement: AtStatement;

    async fn query(&self, sql: impl AsRef<str> + Send + Sync, params: impl AtIntoParams + Send) -> Result<Self::Rows, BoxError>;
    async fn execute(&self, sql: impl AsRef<str> + Send + Sync, params: impl AtIntoParams + Send) -> Result<u64, BoxError>;
    async fn prepare(&self, sql: impl AsRef<str> + Send + Sync) -> Result<Self::Statement, BoxError>;
}

/// Abstraction layer for sql prepared statements
#[async_trait]
pub trait AtStatement: Sized + Send + Sync {
    type Rows: AtRows;

    async fn query(&mut self, params: impl AtIntoParams + Send) -> Result<Self::Rows, BoxError>;
}

/// Abstraction layer for turning array into params
pub trait AtIntoParams: Sized + Send {
    fn into_params(self) -> Result<AtParams, BoxError>;
}

/// Abstraction layer for turning value into sql
pub trait AtIntoValue: Sized + Clone + Send {
    fn into_value(self) -> Result<AtValue, BoxError>;
}

/// Abstraction layer for sql results
#[async_trait]
pub trait AtRows: Sized + Send + Sync {
    type Row: AtRow;

    fn column_count(&self) -> usize;
    async fn next(&mut self) -> Result<Option<Self::Row>, BoxError>;
}

/// Abstraction layer for sql result
pub trait AtRow: Sized + Send + Sync {
    fn get_value(&self, idx: usize) -> Result<AtValue, BoxError>;
    fn get<T>(&self, idx: usize) -> Result<T, BoxError>
    where
      T: AtFromValue;
    fn column_count(&self) -> usize;
}

/// Abstraction layer for turning sql into value
pub trait AtFromValue: Sized + Send {
    fn from_sql(val: AtValue) -> Result<Self, BoxError>
    where
      Self: Sized;
}

/// Abstraction layer for sql parameters
#[derive(Debug, Clone)]
pub enum AtParams {
    None,
    Positional(Vec<AtValue>),
    Named(Vec<(Cow<'static, str>, AtValue)>),
}

/// Abstraction layer for value
#[derive(Clone, Debug, PartialEq)]
pub enum AtValue {
    Null,
    Integer(i64),
    Real(f64),
    Text(String),
    Blob(Vec<u8>),
}

/// Trait used to differentiate between traits that are not implemented
pub trait AtCodecMarker {}

#[derive(Serialize)]
pub struct Paginated<T>
where T : Serialize {
    pub count: u32,
    pub pages: u32,
    pub page: u32,
    pub page_size: u32,
    pub content: Vec<T>
}

impl AtValue {
    pub fn is_null(&self) -> bool {
        matches!(self, Self::Null)
    }

    pub fn is_integer(&self) -> bool {
        matches!(self, Self::Integer(..))
    }

    pub fn is_real(&self) -> bool {
        matches!(self, Self::Real(..))
    }

    pub fn as_real(&self) -> Option<&f64> {
        if let Self::Real(v) = self {
            Some(v)
        } else {
            None
        }
    }

    pub fn is_text(&self) -> bool {
        matches!(self, Self::Text(..))
    }

    pub fn as_text(&self) -> Option<&String> {
        if let Self::Text(v) = self {
            Some(v)
        } else {
            None
        }
    }

    pub fn as_integer(&self) -> Option<&i64> {
        if let Self::Integer(v) = self {
            Some(v)
        } else {
            None
        }
    }

    pub fn is_blob(&self) -> bool {
        matches!(self, Self::Blob(..))
    }

    pub fn as_blob(&self) -> Option<&Vec<u8>> {
        if let Self::Blob(v) = self {
            Some(v)
        } else {
            None
        }
    }
}

// Mark: Useful functions

/// Sync the database table for `T` against the connection.
/// !! Indexes are only created and not monitored !!
///
/// | State          | Action                                      |
/// |--------------- |---------------------------------------------|
/// | Table missing  | `CREATE TABLE`                              |
/// | Column added   | `ALTER TABLE … ADD COLUMN`                  |
/// | Column removed | `ALTER TABLE … DROP COLUMN`                 |
pub async fn sync_table<T: AutoTable>(conn: &impl AtConnection) -> Result<(), BoxError> {
    let table_name = T::table_name();
    let col_defs   = T::column_definitions();

    let existing: HashSet<String> = get_columns(conn, table_name).await?.into_iter().collect();

    if existing.is_empty() {
        // CREATE TABLE
        let sql = generate_create_table(table_name, &col_defs);
        conn.execute(sql, no_params()).await?;
        debug!("Created table `{}`", table_name);
    } else {
        let defined: HashSet<&str> =
            col_defs.iter().map(|c| c.name).collect();

        // ADD new columns
        for col in col_defs.iter().filter(|c| !existing.contains(c.name)) {
            let sql = format!("ALTER TABLE {} ADD COLUMN {}", table_name, col.to_sql());
            conn.execute(sql, no_params()).await?;
            debug!("Added   `{}.{}`", table_name, col.name);
        }

        // DROP removed columns
        for old in existing.iter().filter(|c| !defined.contains(c.as_str())) {
            let sql = format!("ALTER TABLE {} DROP COLUMN {}", table_name, old.to_string());
            conn.execute(sql, no_params()).await?;
            debug!("Dropped `{}.{}`", table_name, old);
        }
    }

    if let Some(indexes) = T::indexes() {
        let sql = format!("CREATE INDEX IF NOT EXISTS idx_auto_table ON {} ({})", table_name, indexes);
        conn.execute(sql, no_params()).await?;
    }

    debug!("Finished sync on `{}`", table_name);
    Ok(())
}
